-- Ajustes na taxonomia (rodar DEPOIS de 002 e 003, em produção já implantada):
--   1. Nova subcategoria "Outras Licenças Remuneradas (Múltiplos Tipos na Mesma Cláusula)"
--      para cláusulas que concedem mais de um tipo de licença no mesmo texto
--      (ex.: "3 dias por casamento e 2 dias por luto" na CLÁUSULA QUADRAGÉSIMA QUINTA).
--   2. Contribuição Assistencial e Contribuição Sindical/Confederativa separadas em
--      Empregado / Patronal.
--   3. Novas subcategorias: Mensalidade Sindical Empregado, Mensalidade Sindical Empresa,
--      Taxa de Abertura/Funcionamento.
--
-- Este script SÓ remapeia cláusulas cujo texto de subcategoria mudou de sentido/nome;
-- é seguro rodar mais de uma vez (idempotente).
--
-- ATENÇÃO — AÇÃO MANUAL RECOMENDADA (item 1):
-- Como o mapa antigo tinha um bug (o valor genérico "Licenças Remuneradas" caía por engano
-- em "Licença Não Remunerada"), cláusulas que hoje estão como "Licença Não Remunerada" MAS que
-- na verdade combinam mais de um tipo de licença (como o exemplo do casamento+luto) NÃO serão
-- corrigidas automaticamente por este script, porque o texto já foi trocado para o nome
-- canônico "Licença Não Remunerada" na migração anterior (não dá mais para saber, só pelo
-- texto salvo, que aquela cláusula era originalmente "Licenças Remuneradas" genérico).
-- Rode a consulta abaixo para achar essas cláusulas e reclassifique manualmente na tela de
-- revisão (Instrumentos → reabrir revisão do instrumento):
--
--   select c.id, c.numero, c.titulo, c.conteudo, i.nome as instrumento
--   from clausulas c join instrumentos i on i.id = c.instrumento_id
--   where c.subcategoria = 'Licença Não Remunerada'
--     and c.conteudo ~* '(casamento|gala).*?(luto|falecimento|nojo)|(luto|falecimento|nojo).*?(casamento|gala)';
--
-- (a expressão busca cláusulas que mencionam casamento E luto/falecimento no mesmo texto —
-- ajuste os termos se seu caso for outra combinação, ex. doação de sangue + alistamento etc.)

create extension if not exists unaccent;

create or replace function _normalizar_chave(txt text) returns text as $$
  select trim(
    regexp_replace(
      regexp_replace(lower(unaccent(coalesce(txt, ''))), '[-–—/()]', ' ', 'g'),
      '\s+', ' ', 'g'
    )
  )
$$ language sql immutable;

drop table if exists _mapa_subcategorias_v2;
create temporary table _mapa_subcategorias_v2 (
  chave text primary key,
  categoria text not null,
  subcategoria text not null
);

insert into _mapa_subcategorias_v2 (chave, categoria, subcategoria) values
  ('piso salarial', 'Remuneração e Reajuste', 'Piso Salarial'),
  ('salario normativo', 'Remuneração e Reajuste', 'Piso Salarial'),
  ('reajuste salarial', 'Remuneração e Reajuste', 'Reajuste Salarial'),
  ('reajuste', 'Remuneração e Reajuste', 'Reajuste Salarial'),
  ('reajustes correcoes salariais', 'Remuneração e Reajuste', 'Reajuste Salarial'),
  ('correcao salarial', 'Remuneração e Reajuste', 'Reajuste Salarial'),
  ('perdas salariais', 'Remuneração e Reajuste', 'Reajuste Salarial'),
  ('equiparacao isonomia salarial', 'Remuneração e Reajuste', 'Equiparação/Isonomia Salarial'),
  ('equiparacao salarial', 'Remuneração e Reajuste', 'Equiparação/Isonomia Salarial'),
  ('isonomia salarial', 'Remuneração e Reajuste', 'Equiparação/Isonomia Salarial'),
  ('salario substituicao', 'Remuneração e Reajuste', 'Salário Substituição'),
  ('gratificacao', 'Remuneração e Reajuste', 'Gratificação'),
  ('gratificacao por tempo de servico', 'Remuneração e Reajuste', 'Gratificação por Tempo de Serviço'),
  ('premio por tempo de servico', 'Remuneração e Reajuste', 'Gratificação por Tempo de Serviço'),
  ('gratificacao por aposentadoria', 'Remuneração e Reajuste', 'Gratificação por Aposentadoria'),
  ('premio de producao desempenho', 'Remuneração e Reajuste', 'Prêmio de Produção/Desempenho'),
  ('premio producao', 'Remuneração e Reajuste', 'Prêmio de Produção/Desempenho'),
  ('premio de producao', 'Remuneração e Reajuste', 'Prêmio de Produção/Desempenho'),
  ('premio desempenho', 'Remuneração e Reajuste', 'Prêmio de Produção/Desempenho'),
  ('participacao em metas', 'Remuneração e Reajuste', 'Participação em Metas'),
  ('plr ppr', 'Remuneração e Reajuste', 'PLR/PPR'),
  ('plr', 'Remuneração e Reajuste', 'PLR/PPR'),
  ('ppr', 'Remuneração e Reajuste', 'PLR/PPR'),
  ('comissao', 'Remuneração e Reajuste', 'Comissão'),
  ('adicional de funcao', 'Remuneração e Reajuste', 'Adicional de Função'),
  ('adicional de acumulo de funcao', 'Remuneração e Reajuste', 'Adicional de Acúmulo de Função'),
  ('adicional noturno', 'Remuneração e Reajuste', 'Adicional Noturno'),
  ('adicional de transferencia', 'Remuneração e Reajuste', 'Adicional de Transferência'),
  ('adicional de penosidade', 'Remuneração e Reajuste', 'Adicional de Penosidade'),
  ('quebra de caixa', 'Remuneração e Reajuste', 'Quebra de Caixa'),
  ('promocao progressao salarial', 'Remuneração e Reajuste', 'Promoção/Progressão Salarial'),
  ('promocao salarial', 'Remuneração e Reajuste', 'Promoção/Progressão Salarial'),
  ('progressao salarial', 'Remuneração e Reajuste', 'Promoção/Progressão Salarial'),
  ('complementacao salarial auxilio doenca acidente', 'Remuneração e Reajuste', 'Complementação Salarial (Auxílio-Doença/Acidente)'),
  ('complementacao salarial', 'Remuneração e Reajuste', 'Complementação Salarial (Auxílio-Doença/Acidente)'),
  ('complementacao de auxilio doenca', 'Remuneração e Reajuste', 'Complementação Salarial (Auxílio-Doença/Acidente)'),
  ('13º salario', 'Remuneração e Reajuste', '13º Salário'),
  ('13o salario', 'Remuneração e Reajuste', '13º Salário'),
  ('decimo terceiro', 'Remuneração e Reajuste', '13º Salário'),
  ('comprovante de pagamento', 'Remuneração e Reajuste', 'Comprovante de Pagamento'),
  ('comprovantes e anotacoes', 'Remuneração e Reajuste', 'Comprovante de Pagamento'),
  ('pagamento de salario', 'Remuneração e Reajuste', 'Comprovante de Pagamento'),
  ('descontos em folha', 'Remuneração e Reajuste', 'Descontos em Folha'),
  ('descontos salariais', 'Remuneração e Reajuste', 'Descontos em Folha'),
  ('dsr', 'Remuneração e Reajuste', 'DSR'),
  ('descanso semanal remunerado', 'Remuneração e Reajuste', 'DSR'),
  ('adiantamento salarial', 'Remuneração e Reajuste', 'Adiantamento Salarial'),
  ('forma e prazo de pagamento', 'Remuneração e Reajuste', 'Forma e Prazo de Pagamento'),
  ('forma de pagamento', 'Remuneração e Reajuste', 'Forma e Prazo de Pagamento'),
  ('prazo de pagamento', 'Remuneração e Reajuste', 'Forma e Prazo de Pagamento'),
  ('base de calculo salarial', 'Remuneração e Reajuste', 'Base de Cálculo Salarial'),
  ('base de calculo', 'Remuneração e Reajuste', 'Base de Cálculo Salarial'),
  ('duracao da jornada', 'Jornada de Trabalho', 'Duração da Jornada'),
  ('interrupcao do trabalho', 'Jornada de Trabalho', 'Duração da Jornada'),
  ('interrupcoes de trabalho', 'Jornada de Trabalho', 'Duração da Jornada'),
  ('banco de horas', 'Jornada de Trabalho', 'Banco de Horas'),
  ('hora extra', 'Jornada de Trabalho', 'Hora Extra'),
  ('horas extras', 'Jornada de Trabalho', 'Hora Extra'),
  ('apuracao de horas extras', 'Jornada de Trabalho', 'Hora Extra'),
  ('compensacao de jornada', 'Jornada de Trabalho', 'Compensação de Jornada'),
  ('compensacao de horas', 'Jornada de Trabalho', 'Compensação de Jornada'),
  ('controle de ponto', 'Jornada de Trabalho', 'Controle de Ponto'),
  ('controle de jornada', 'Jornada de Trabalho', 'Controle de Ponto'),
  ('controle de jornada externa', 'Jornada de Trabalho', 'Controle de Ponto'),
  ('registro eletronico de ponto', 'Jornada de Trabalho', 'Registro Eletrônico de Ponto'),
  ('registro de ponto por excecao', 'Jornada de Trabalho', 'Registro de Ponto por Exceção'),
  ('registro por excecao', 'Jornada de Trabalho', 'Registro de Ponto por Exceção'),
  ('tolerancia de ponto', 'Jornada de Trabalho', 'Tolerância de Ponto'),
  ('intervalo intrajornada', 'Jornada de Trabalho', 'Intervalo Intrajornada'),
  ('intervalo remunerado', 'Jornada de Trabalho', 'Intervalo Intrajornada'),
  ('intervalos', 'Jornada de Trabalho', 'Intervalo Intrajornada'),
  ('intervalo interjornada', 'Jornada de Trabalho', 'Intervalo Interjornada'),
  ('trabalho noturno', 'Jornada de Trabalho', 'Trabalho Noturno'),
  ('sobreaviso', 'Jornada de Trabalho', 'Sobreaviso'),
  ('convocacao extraordinaria', 'Jornada de Trabalho', 'Convocação Extraordinária'),
  ('jornada reduzida', 'Jornada de Trabalho', 'Jornada Reduzida'),
  ('jornada externa', 'Jornada de Trabalho', 'Jornada Externa'),
  ('tempo a disposicao', 'Jornada de Trabalho', 'Tempo à Disposição'),
  ('escala de trabalho', 'Jornada de Trabalho', 'Escala de Trabalho'),
  ('escala', 'Jornada de Trabalho', 'Escala de Trabalho'),
  ('jornada flexivel para motoristas', 'Jornada de Trabalho', 'Escala de Trabalho'),
  ('turnos de revezamento', 'Jornada de Trabalho', 'Turnos de Revezamento'),
  ('turno', 'Jornada de Trabalho', 'Turnos de Revezamento'),
  ('trabalho aos domingos', 'Jornada de Trabalho', 'Trabalho aos Domingos'),
  ('trabalho em feriados', 'Jornada de Trabalho', 'Trabalho em Feriados'),
  ('teletrabalho home office', 'Jornada de Trabalho', 'Teletrabalho/Home Office'),
  ('teletrabalho', 'Jornada de Trabalho', 'Teletrabalho/Home Office'),
  ('home office', 'Jornada de Trabalho', 'Teletrabalho/Home Office'),
  ('trabalho hibrido', 'Jornada de Trabalho', 'Trabalho Híbrido'),
  ('abono de faltas', 'Jornada de Trabalho', 'Abono de Faltas'),
  ('flexibilidade para estudantes', 'Jornada de Trabalho', 'Flexibilidade para Estudantes'),
  ('vale alimentacao auxilio alimentacao', 'Benefícios', 'Vale-Alimentação/Auxílio Alimentação'),
  ('vale alimentacao', 'Benefícios', 'Vale-Alimentação/Auxílio Alimentação'),
  ('auxilio alimentacao', 'Benefícios', 'Vale-Alimentação/Auxílio Alimentação'),
  ('alimentacao', 'Benefícios', 'Vale-Alimentação/Auxílio Alimentação'),
  ('ticket refeicao alimentacao', 'Benefícios', 'Vale-Alimentação/Auxílio Alimentação'),
  ('vale refeicao', 'Benefícios', 'Vale-Refeição'),
  ('lanche', 'Benefícios', 'Lanche'),
  ('fornecimento de lanche', 'Benefícios', 'Lanche'),
  ('alimentacao no local de trabalho refeitorio', 'Benefícios', 'Alimentação no Local de Trabalho (Refeitório)'),
  ('alimentacao no local de trabalho', 'Benefícios', 'Alimentação no Local de Trabalho (Refeitório)'),
  ('refeitorio', 'Benefícios', 'Alimentação no Local de Trabalho (Refeitório)'),
  ('vale transporte', 'Benefícios', 'Vale-Transporte'),
  ('vale combustivel', 'Benefícios', 'Vale-Combustível'),
  ('transporte fornecido pela empresa', 'Benefícios', 'Transporte Fornecido pela Empresa'),
  ('fretado', 'Benefícios', 'Transporte Fornecido pela Empresa'),
  ('cesta basica', 'Benefícios', 'Cesta Básica'),
  ('beneficio assistencial social familiar', 'Benefícios', 'Benefício Assistencial Social/Familiar'),
  ('beneficio assistencial social', 'Benefícios', 'Benefício Assistencial Social/Familiar'),
  ('beneficio assistencial familiar', 'Benefícios', 'Benefício Assistencial Social/Familiar'),
  ('assistencia social ao empregado', 'Benefícios', 'Benefício Assistencial Social/Familiar'),
  ('auxilio creche', 'Benefícios', 'Auxílio Creche'),
  ('auxilio moradia', 'Benefícios', 'Auxílio Moradia'),
  ('auxilio educacao bolsa de estudos', 'Benefícios', 'Auxílio Educação/Bolsa de Estudos'),
  ('auxilio educacao', 'Benefícios', 'Auxílio Educação/Bolsa de Estudos'),
  ('bolsa de estudos', 'Benefícios', 'Auxílio Educação/Bolsa de Estudos'),
  ('auxilio internet home office', 'Benefícios', 'Auxílio Internet/Home Office'),
  ('auxilio internet', 'Benefícios', 'Auxílio Internet/Home Office'),
  ('auxilio home office', 'Benefícios', 'Auxílio Internet/Home Office'),
  ('auxilio mobilidade', 'Benefícios', 'Auxílio Mobilidade'),
  ('plano de saude', 'Benefícios', 'Plano de Saúde'),
  ('convenio medico', 'Benefícios', 'Plano de Saúde'),
  ('extensao de beneficios', 'Benefícios', 'Plano de Saúde'),
  ('pat', 'Benefícios', 'Plano de Saúde'),
  ('plano odontologico', 'Benefícios', 'Plano Odontológico'),
  ('assistencia odontologica', 'Benefícios', 'Plano Odontológico'),
  ('assistencia odontologica pts', 'Benefícios', 'Plano Odontológico'),
  ('seguro de vida e auxilio funeral', 'Benefícios', 'Seguro de Vida e Auxílio Funeral'),
  ('seguro de vida', 'Benefícios', 'Seguro de Vida e Auxílio Funeral'),
  ('seguro de vida e fundo de inclusao social', 'Benefícios', 'Seguro de Vida e Auxílio Funeral'),
  ('auxilio funeral', 'Benefícios', 'Seguro de Vida e Auxílio Funeral'),
  ('auxilio funeral transporte', 'Benefícios', 'Seguro de Vida e Auxílio Funeral'),
  ('auxilio farmacia', 'Benefícios', 'Auxílio Farmácia'),
  ('convenio farmacia', 'Benefícios', 'Auxílio Farmácia'),
  ('auxilio doenca acidente', 'Benefícios', 'Auxílio Doença/Acidente'),
  ('auxilio filho com deficiencia', 'Benefícios', 'Auxílio Filho com Deficiência'),
  ('auxilio filho excepcional', 'Benefícios', 'Auxílio Filho com Deficiência'),
  ('previdencia privada', 'Benefícios', 'Previdência Privada'),
  ('previdencia social', 'Benefícios', 'Previdência Privada'),
  ('emprestimos consignados', 'Benefícios', 'Empréstimos Consignados'),
  ('convenios e descontos diversos', 'Benefícios', 'Convênios e Descontos (Diversos)'),
  ('convenios e descontos', 'Benefícios', 'Convênios e Descontos (Diversos)'),
  ('reembolso de despesas diarias de viagem', 'Benefícios', 'Reembolso de Despesas/Diárias de Viagem'),
  ('reembolso de despesas de viagem', 'Benefícios', 'Reembolso de Despesas/Diárias de Viagem'),
  ('reembolso de despesas de viagem diarias', 'Benefícios', 'Reembolso de Despesas/Diárias de Viagem'),
  ('manutencao de beneficios', 'Benefícios', 'Manutenção de Benefícios'),
  ('natureza nao salarial de beneficios', 'Benefícios', 'Natureza Não Salarial de Benefícios'),
  ('natureza juridica de beneficios', 'Benefícios', 'Natureza Não Salarial de Benefícios'),
  ('nao incorporacao de beneficios', 'Benefícios', 'Natureza Não Salarial de Benefícios'),
  ('outros beneficios', 'Benefícios', 'Outros Benefícios'),
  ('insalubridade', 'Saúde e Segurança do Trabalho', 'Insalubridade'),
  ('periculosidade', 'Saúde e Segurança do Trabalho', 'Periculosidade'),
  ('adicional de periculosidade', 'Saúde e Segurança do Trabalho', 'Periculosidade'),
  ('adicionais de insalubridade periculosidade', 'Saúde e Segurança do Trabalho', 'Adicionais de Insalubridade/Periculosidade'),
  ('insalubridade periculosidade', 'Saúde e Segurança do Trabalho', 'Adicionais de Insalubridade/Periculosidade'),
  ('insalubridade e periculosidade', 'Saúde e Segurança do Trabalho', 'Adicionais de Insalubridade/Periculosidade'),
  ('adicionais de insalubridade periculosidade e protecao a maternidade', 'Saúde e Segurança do Trabalho', 'Adicionais de Insalubridade/Periculosidade'),
  ('epi', 'Saúde e Segurança do Trabalho', 'EPI'),
  ('equipamentos de protecao', 'Saúde e Segurança do Trabalho', 'EPI'),
  ('equipamentos de protecao individual epi', 'Saúde e Segurança do Trabalho', 'EPI'),
  ('epi e exames medicos', 'Saúde e Segurança do Trabalho', 'EPI'),
  ('fornecimento de uniformes', 'Saúde e Segurança do Trabalho', 'EPI'),
  ('exames medicos', 'Saúde e Segurança do Trabalho', 'Exames Médicos'),
  ('exames medicos periodicos', 'Saúde e Segurança do Trabalho', 'Exames Médicos'),
  ('atestados medicos', 'Saúde e Segurança do Trabalho', 'Atestados Médicos'),
  ('aceitacao de atestados', 'Saúde e Segurança do Trabalho', 'Atestados Médicos'),
  ('validade de atestados medicos', 'Saúde e Segurança do Trabalho', 'Atestados Médicos'),
  ('cipa', 'Saúde e Segurança do Trabalho', 'CIPA'),
  ('sesmt', 'Saúde e Segurança do Trabalho', 'SESMT'),
  ('sipat', 'Saúde e Segurança do Trabalho', 'SIPAT'),
  ('pcmso ppra pgr', 'Saúde e Segurança do Trabalho', 'PCMSO/PPRA/PGR'),
  ('pcmso', 'Saúde e Segurança do Trabalho', 'PCMSO/PPRA/PGR'),
  ('ppra', 'Saúde e Segurança do Trabalho', 'PCMSO/PPRA/PGR'),
  ('pgr', 'Saúde e Segurança do Trabalho', 'PCMSO/PPRA/PGR'),
  ('pcmso ppra', 'Saúde e Segurança do Trabalho', 'PCMSO/PPRA/PGR'),
  ('ppra pgr', 'Saúde e Segurança do Trabalho', 'PCMSO/PPRA/PGR'),
  ('ergonomia', 'Saúde e Segurança do Trabalho', 'Ergonomia'),
  ('saude mental e fatores psicossociais nr 01', 'Saúde e Segurança do Trabalho', 'Saúde Mental e Fatores Psicossociais (NR-01)'),
  ('saude mental', 'Saúde e Segurança do Trabalho', 'Saúde Mental e Fatores Psicossociais (NR-01)'),
  ('fatores psicossociais', 'Saúde e Segurança do Trabalho', 'Saúde Mental e Fatores Psicossociais (NR-01)'),
  ('nr 01', 'Saúde e Segurança do Trabalho', 'Saúde Mental e Fatores Psicossociais (NR-01)'),
  ('nr01', 'Saúde e Segurança do Trabalho', 'Saúde Mental e Fatores Psicossociais (NR-01)'),
  ('dependencia quimica', 'Saúde e Segurança do Trabalho', 'Dependência Química'),
  ('programa de bem estar', 'Saúde e Segurança do Trabalho', 'Programa de Bem-Estar'),
  ('vacinacao', 'Saúde e Segurança do Trabalho', 'Vacinação'),
  ('brigada de incendio', 'Saúde e Segurança do Trabalho', 'Brigada de Incêndio'),
  ('acidente de trabalho', 'Saúde e Segurança do Trabalho', 'Acidente de Trabalho'),
  ('assistencia medica em acidente de trabalho', 'Saúde e Segurança do Trabalho', 'Acidente de Trabalho'),
  ('prevencao de acidentes e doencas', 'Saúde e Segurança do Trabalho', 'Prevenção de Acidentes e Doenças'),
  ('prevencao de acidentes e doencas profissionais', 'Saúde e Segurança do Trabalho', 'Prevenção de Acidentes e Doenças'),
  ('uniformes', 'Saúde e Segurança do Trabalho', 'Uniformes'),
  ('uniformes e lavagem', 'Saúde e Segurança do Trabalho', 'Uniformes'),
  ('treinamento e informacao em seguranca', 'Saúde e Segurança do Trabalho', 'Treinamento e Informação em Segurança'),
  ('treinamento e informacao', 'Saúde e Segurança do Trabalho', 'Treinamento e Informação em Segurança'),
  ('direito de recusa', 'Saúde e Segurança do Trabalho', 'Direito de Recusa'),
  ('condicoes de ambiente de trabalho', 'Saúde e Segurança do Trabalho', 'Condições de Ambiente de Trabalho'),
  ('nr especifica', 'Saúde e Segurança do Trabalho', 'NR Específica'),
  ('estabilidade gestante', 'Estabilidade e Garantias de Emprego', 'Estabilidade Gestante'),
  ('estabilidade acidentado doenca profissional', 'Estabilidade e Garantias de Emprego', 'Estabilidade Acidentado/Doença Profissional'),
  ('estabilidade acidente de trabalho', 'Estabilidade e Garantias de Emprego', 'Estabilidade Acidentado/Doença Profissional'),
  ('estabilidade pos acidente doenca profissional', 'Estabilidade e Garantias de Emprego', 'Estabilidade Acidentado/Doença Profissional'),
  ('estabilidade pre aposentadoria', 'Estabilidade e Garantias de Emprego', 'Estabilidade Pré-Aposentadoria'),
  ('pre aposentadoria', 'Estabilidade e Garantias de Emprego', 'Estabilidade Pré-Aposentadoria'),
  ('garantia pre aposentadoria', 'Estabilidade e Garantias de Emprego', 'Estabilidade Pré-Aposentadoria'),
  ('estabilidade dirigente sindical cipeiro', 'Estabilidade e Garantias de Emprego', 'Estabilidade Dirigente Sindical/Cipeiro'),
  ('dirigente sindical', 'Estabilidade e Garantias de Emprego', 'Estabilidade Dirigente Sindical/Cipeiro'),
  ('cipeiro', 'Estabilidade e Garantias de Emprego', 'Estabilidade Dirigente Sindical/Cipeiro'),
  ('estabilidade dirigente sindical', 'Estabilidade e Garantias de Emprego', 'Estabilidade Dirigente Sindical/Cipeiro'),
  ('estabilidade eleitoral interna', 'Estabilidade e Garantias de Emprego', 'Estabilidade Eleitoral Interna'),
  ('estabilidade servico militar', 'Estabilidade e Garantias de Emprego', 'Estabilidade Serviço Militar'),
  ('garantia de retorno ao trabalho', 'Estabilidade e Garantias de Emprego', 'Garantia de Retorno ao Trabalho'),
  ('garantia ao afastado previdenciario', 'Estabilidade e Garantias de Emprego', 'Garantia ao Afastado Previdenciário'),
  ('garantia por transferencia', 'Estabilidade e Garantias de Emprego', 'Garantia por Transferência'),
  ('garantias gerais de emprego', 'Estabilidade e Garantias de Emprego', 'Garantias Gerais de Emprego'),
  ('dispensa coletiva', 'Estabilidade e Garantias de Emprego', 'Dispensa Coletiva'),
  ('contrato de experiencia', 'Estabilidade e Garantias de Emprego', 'Contrato de Experiência'),
  ('ferias', 'Férias e Licenças', 'Férias'),
  ('concessao de ferias', 'Férias e Licenças', 'Férias'),
  ('ferias proporcionais na rescisao', 'Férias e Licenças', 'Férias'),
  ('abono de ferias', 'Férias e Licenças', 'Abono de Férias'),
  ('gratificacao de ferias', 'Férias e Licenças', 'Abono de Férias'),
  ('concessao programacao de ferias', 'Férias e Licenças', 'Concessão/Programação de Férias'),
  ('programacao de ferias', 'Férias e Licenças', 'Concessão/Programação de Férias'),
  ('ferias coletivas', 'Férias e Licenças', 'Férias Coletivas'),
  ('fracionamento de ferias', 'Férias e Licenças', 'Fracionamento de Férias'),
  ('licenca maternidade', 'Férias e Licenças', 'Licença Maternidade'),
  ('licenca paternidade', 'Férias e Licenças', 'Licença Paternidade'),
  ('licenca adocao', 'Férias e Licenças', 'Licença Adoção'),
  ('licenca amamentacao', 'Férias e Licenças', 'Licença Amamentação'),
  ('licenca casamento gala', 'Férias e Licenças', 'Licença Casamento (Gala)'),
  ('licenca casamento', 'Férias e Licenças', 'Licença Casamento (Gala)'),
  ('licenca gala', 'Férias e Licenças', 'Licença Casamento (Gala)'),
  ('licenca nojo luto', 'Férias e Licenças', 'Licença Nojo/Luto'),
  ('licenca nojo', 'Férias e Licenças', 'Licença Nojo/Luto'),
  ('licenca luto', 'Férias e Licenças', 'Licença Nojo/Luto'),
  ('licenca para acompanhamento medico filho dependente', 'Férias e Licenças', 'Licença para Acompanhamento Médico (Filho/Dependente)'),
  ('licenca para acompanhamento medico', 'Férias e Licenças', 'Licença para Acompanhamento Médico (Filho/Dependente)'),
  ('licenca para doacao de sangue', 'Férias e Licenças', 'Licença para Doação de Sangue'),
  ('licenca para alistamento eleitoral', 'Férias e Licenças', 'Licença para Alistamento Eleitoral'),
  ('licenca para servico militar', 'Férias e Licenças', 'Licença para Serviço Militar'),
  ('licenca para comparecimento a juizo', 'Férias e Licenças', 'Licença para Comparecimento a Juízo'),
  ('licenca para exame vestibular', 'Férias e Licenças', 'Licença para Exame Vestibular'),
  ('licenca nao remunerada', 'Férias e Licenças', 'Licença Não Remunerada'),
  ('licenca premio', 'Férias e Licenças', 'Licença Prêmio'),
  ('outras licencas remuneradas multiplos tipos na mesma clausula', 'Férias e Licenças', 'Outras Licenças Remuneradas (Múltiplos Tipos na Mesma Cláusula)'),
  ('outras licencas remuneradas', 'Férias e Licenças', 'Outras Licenças Remuneradas (Múltiplos Tipos na Mesma Cláusula)'),
  ('licencas remuneradas diversas', 'Férias e Licenças', 'Outras Licenças Remuneradas (Múltiplos Tipos na Mesma Cláusula)'),
  ('licencas remuneradas', 'Férias e Licenças', 'Outras Licenças Remuneradas (Múltiplos Tipos na Mesma Cláusula)'),
  ('licenca remunerada', 'Férias e Licenças', 'Outras Licenças Remuneradas (Múltiplos Tipos na Mesma Cláusula)'),
  ('fgts', 'FGTS, Verbas e Rescisão Contratual', 'FGTS'),
  ('extrato fgts', 'FGTS, Verbas e Rescisão Contratual', 'FGTS'),
  ('multa rescisoria fgts', 'FGTS, Verbas e Rescisão Contratual', 'Multa Rescisória (FGTS)'),
  ('multa rescisoria', 'FGTS, Verbas e Rescisão Contratual', 'Multa Rescisória (FGTS)'),
  ('verbas rescisorias', 'FGTS, Verbas e Rescisão Contratual', 'Verbas Rescisórias'),
  ('rescisao contratual', 'FGTS, Verbas e Rescisão Contratual', 'Verbas Rescisórias'),
  ('calculo de verbas rescisorias e ferias comissionados', 'FGTS, Verbas e Rescisão Contratual', 'Verbas Rescisórias'),
  ('parcelamento de verbas rescisorias', 'FGTS, Verbas e Rescisão Contratual', 'Parcelamento de Verbas Rescisórias'),
  ('homologacao de rescisao', 'FGTS, Verbas e Rescisão Contratual', 'Homologação de Rescisão'),
  ('homologacao', 'FGTS, Verbas e Rescisão Contratual', 'Homologação de Rescisão'),
  ('homologacao sindical', 'FGTS, Verbas e Rescisão Contratual', 'Homologação Sindical'),
  ('aviso previo', 'FGTS, Verbas e Rescisão Contratual', 'Aviso Prévio'),
  ('comunicacao de aviso previo', 'FGTS, Verbas e Rescisão Contratual', 'Aviso Prévio'),
  ('aviso previo diferenciado', 'FGTS, Verbas e Rescisão Contratual', 'Aviso Prévio'),
  ('dispensa de cumprimento de aviso previo', 'FGTS, Verbas e Rescisão Contratual', 'Dispensa de Cumprimento de Aviso Prévio'),
  ('pedido de demissao', 'FGTS, Verbas e Rescisão Contratual', 'Pedido de Demissão'),
  ('rescisao por acordo art. 484 a clt', 'FGTS, Verbas e Rescisão Contratual', 'Rescisão por Acordo (Art. 484-A CLT)'),
  ('rescisao por acordo', 'FGTS, Verbas e Rescisão Contratual', 'Rescisão por Acordo (Art. 484-A CLT)'),
  ('art. 484 a', 'FGTS, Verbas e Rescisão Contratual', 'Rescisão por Acordo (Art. 484-A CLT)'),
  ('artigo 484 a', 'FGTS, Verbas e Rescisão Contratual', 'Rescisão por Acordo (Art. 484-A CLT)'),
  ('dispensa por justa causa', 'FGTS, Verbas e Rescisão Contratual', 'Dispensa por Justa Causa'),
  ('plano de demissao voluntaria pdv pdi', 'FGTS, Verbas e Rescisão Contratual', 'Plano de Demissão Voluntária (PDV/PDI)'),
  ('plano de demissao voluntaria', 'FGTS, Verbas e Rescisão Contratual', 'Plano de Demissão Voluntária (PDV/PDI)'),
  ('pdv', 'FGTS, Verbas e Rescisão Contratual', 'Plano de Demissão Voluntária (PDV/PDI)'),
  ('pdi', 'FGTS, Verbas e Rescisão Contratual', 'Plano de Demissão Voluntária (PDV/PDI)'),
  ('seguro desemprego', 'FGTS, Verbas e Rescisão Contratual', 'Seguro-Desemprego'),
  ('quitacao anual', 'FGTS, Verbas e Rescisão Contratual', 'Quitação Anual'),
  ('documentacao de admissao rescisao', 'FGTS, Verbas e Rescisão Contratual', 'Documentação de Admissão/Rescisão'),
  ('documentacao de admissao', 'FGTS, Verbas e Rescisão Contratual', 'Documentação de Admissão/Rescisão'),
  ('documentacao de rescisao', 'FGTS, Verbas e Rescisão Contratual', 'Documentação de Admissão/Rescisão'),
  ('documentacao pos rescisao', 'FGTS, Verbas e Rescisão Contratual', 'Documentação de Admissão/Rescisão'),
  ('documentos pos rescisao', 'FGTS, Verbas e Rescisão Contratual', 'Documentação de Admissão/Rescisão'),
  ('documentacao do empregado', 'FGTS, Verbas e Rescisão Contratual', 'Documentação de Admissão/Rescisão'),
  ('documentacao trabalhista', 'FGTS, Verbas e Rescisão Contratual', 'Documentação de Admissão/Rescisão'),
  ('contrato de trabalho', 'FGTS, Verbas e Rescisão Contratual', 'Documentação de Admissão/Rescisão'),
  ('contribuicao assistencial empregado', 'Relações Sindicais e Representação', 'Contribuição Assistencial Empregado'),
  ('contribuicao assistencial', 'Relações Sindicais e Representação', 'Contribuição Assistencial Empregado'),
  ('contribuicao assistencial empregados', 'Relações Sindicais e Representação', 'Contribuição Assistencial Empregado'),
  ('custeio sindical', 'Relações Sindicais e Representação', 'Contribuição Assistencial Empregado'),
  ('taxa negocial', 'Relações Sindicais e Representação', 'Contribuição Assistencial Empregado'),
  ('contribuicao assistencial patronal', 'Relações Sindicais e Representação', 'Contribuição Assistencial Patronal'),
  ('contribuicao confederativa patronal', 'Relações Sindicais e Representação', 'Contribuição Assistencial Patronal'),
  ('contribuicao permanente patronal', 'Relações Sindicais e Representação', 'Contribuição Assistencial Patronal'),
  ('contribuicao sindical confederativa empregado', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Empregado'),
  ('contribuicoes sindicais', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Empregado'),
  ('contribuicoes sindicais dos empregados', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Empregado'),
  ('contribuicao sindical confederativa', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Empregado'),
  ('contribuicao sindical', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Empregado'),
  ('contribuicao confederativa', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Empregado'),
  ('contribuicao sindical confederativa patronal', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Patronal'),
  ('contribuicoes sindicais patronais', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Patronal'),
  ('contribuicao sindical patronal', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Patronal'),
  ('contribuicao confederativa patronal empresa', 'Relações Sindicais e Representação', 'Contribuição Sindical/Confederativa Patronal'),
  ('mensalidade sindical empregado', 'Relações Sindicais e Representação', 'Mensalidade Sindical Empregado'),
  ('mensalidade associativa', 'Relações Sindicais e Representação', 'Mensalidade Sindical Empregado'),
  ('mensalidade associativa empregado', 'Relações Sindicais e Representação', 'Mensalidade Sindical Empregado'),
  ('mensalidade sindical', 'Relações Sindicais e Representação', 'Mensalidade Sindical Empregado'),
  ('mensalidade sindical empresa', 'Relações Sindicais e Representação', 'Mensalidade Sindical Empresa'),
  ('mensalidade sindical patronal', 'Relações Sindicais e Representação', 'Mensalidade Sindical Empresa'),
  ('mensalidade associativa patronal', 'Relações Sindicais e Representação', 'Mensalidade Sindical Empresa'),
  ('mensalidade associativa empresa', 'Relações Sindicais e Representação', 'Mensalidade Sindical Empresa'),
  ('taxa de abertura funcionamento', 'Relações Sindicais e Representação', 'Taxa de Abertura/Funcionamento'),
  ('taxa de abertura', 'Relações Sindicais e Representação', 'Taxa de Abertura/Funcionamento'),
  ('taxa de funcionamento', 'Relações Sindicais e Representação', 'Taxa de Abertura/Funcionamento'),
  ('taxa de abertura e funcionamento', 'Relações Sindicais e Representação', 'Taxa de Abertura/Funcionamento'),
  ('direito de oposicao', 'Relações Sindicais e Representação', 'Direito de Oposição'),
  ('garantias a dirigentes sindicais', 'Relações Sindicais e Representação', 'Garantias a Dirigentes Sindicais'),
  ('garantias a diretores sindicais', 'Relações Sindicais e Representação', 'Garantias a Dirigentes Sindicais'),
  ('liberacao sindical', 'Relações Sindicais e Representação', 'Garantias a Dirigentes Sindicais'),
  ('liberacao de dirigentes sindicais', 'Relações Sindicais e Representação', 'Garantias a Dirigentes Sindicais'),
  ('licenca para dirigente sindical', 'Relações Sindicais e Representação', 'Garantias a Dirigentes Sindicais'),
  ('licenca remunerada para dirigentes sindicais', 'Relações Sindicais e Representação', 'Garantias a Dirigentes Sindicais'),
  ('informacoes sindicais aos empregados', 'Relações Sindicais e Representação', 'Informações Sindicais aos Empregados'),
  ('informacoes sindicais', 'Relações Sindicais e Representação', 'Informações Sindicais aos Empregados'),
  ('informacoes sobre contribuicoes sindicais', 'Relações Sindicais e Representação', 'Informações Sindicais aos Empregados'),
  ('comunicacao sindical', 'Relações Sindicais e Representação', 'Informações Sindicais aos Empregados'),
  ('fornecimento de documentos e informacoes ao sindicato', 'Relações Sindicais e Representação', 'Fornecimento de Documentos e Informações ao Sindicato'),
  ('fornecimento de documentos ao sindicato', 'Relações Sindicais e Representação', 'Fornecimento de Documentos e Informações ao Sindicato'),
  ('fornecimento de informacoes ao sindicato', 'Relações Sindicais e Representação', 'Fornecimento de Documentos e Informações ao Sindicato'),
  ('assembleia', 'Relações Sindicais e Representação', 'Assembleia'),
  ('negociacao coletiva', 'Relações Sindicais e Representação', 'Negociação Coletiva'),
  ('principios da negociacao', 'Relações Sindicais e Representação', 'Negociação Coletiva'),
  ('apoio sindical', 'Relações Sindicais e Representação', 'Negociação Coletiva'),
  ('obrigacoes sindicais', 'Relações Sindicais e Representação', 'Negociação Coletiva'),
  ('mesa permanente de negociacao', 'Relações Sindicais e Representação', 'Mesa Permanente de Negociação'),
  ('acesso do sindicato ao local de trabalho', 'Relações Sindicais e Representação', 'Acesso do Sindicato ao Local de Trabalho'),
  ('acesso do sindicato', 'Relações Sindicais e Representação', 'Acesso do Sindicato ao Local de Trabalho'),
  ('acesso do sindicato a empresa', 'Relações Sindicais e Representação', 'Acesso do Sindicato ao Local de Trabalho'),
  ('quadro de avisos sindical', 'Relações Sindicais e Representação', 'Quadro de Avisos Sindical'),
  ('quadro de avisos', 'Relações Sindicais e Representação', 'Quadro de Avisos Sindical'),
  ('compromisso de nao paralisacao', 'Relações Sindicais e Representação', 'Compromisso de Não Paralisação'),
  ('compromisso de nao paralisacao e negociacao futura', 'Relações Sindicais e Representação', 'Compromisso de Não Paralisação'),
  ('vedacao de conduta antissindical', 'Relações Sindicais e Representação', 'Vedação de Conduta Antissindical'),
  ('comissao de conciliacao previa ccp', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa composicao', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa conciliacao parcial', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa convocacao e documentacao', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa definicao e obrigatoriedade', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa horario e tolerancia', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa local de instalacao', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa recebimento de reclamacoes', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa tentativa frustrada', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('comissao de conciliacao previa termo de conciliacao', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('composicao da ccp', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('horario de reunioes da ccp', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('local de funcionamento da ccp', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('natureza e obrigatoriedade da ccp', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('prazos e convocacao da ccp', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('procedimento de reclamacao na ccp', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('camara de conciliacao trabalhista', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('conciliacao previa', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('efeitos da conciliacao parcial', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('efeitos do termo de conciliacao', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('procedimento em caso de conciliacao frustrada', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Comissão de Conciliação Prévia (CCP)'),
  ('mediacao', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Mediação'),
  ('arbitragem', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Arbitragem'),
  ('resolucao de conflitos e duvidas', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Resolução de Conflitos e Dúvidas'),
  ('resolucao de conflitos', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Resolução de Conflitos e Dúvidas'),
  ('resolucao de duvidas e conflitos', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Resolução de Conflitos e Dúvidas'),
  ('mecanismos de solucao de conflitos', 'Comissão de Conciliação Prévia e Resolução de Conflitos', 'Resolução de Conflitos e Dúvidas'),
  ('multa por descumprimento', 'Penalidades', 'Multa por Descumprimento'),
  ('multa por descumprimento da cct', 'Penalidades', 'Multa por Descumprimento'),
  ('comunicacao de penalidades', 'Penalidades', 'Multa por Descumprimento'),
  ('clausula penal', 'Penalidades', 'Cláusula Penal'),
  ('advertencia', 'Penalidades', 'Advertência'),
  ('suspensao disciplinar', 'Penalidades', 'Suspensão Disciplinar'),
  ('suspensao', 'Penalidades', 'Suspensão Disciplinar'),
  ('ressarcimento de danos responsabilidade por perdas', 'Penalidades', 'Ressarcimento de Danos/Responsabilidade por Perdas'),
  ('ressarcimento de danos', 'Penalidades', 'Ressarcimento de Danos/Responsabilidade por Perdas'),
  ('responsabilidade por perdas', 'Penalidades', 'Ressarcimento de Danos/Responsabilidade por Perdas'),
  ('treinamento obrigatorio', 'Capacitação e Desenvolvimento', 'Treinamento Obrigatório'),
  ('qualificacao profissional', 'Capacitação e Desenvolvimento', 'Qualificação Profissional'),
  ('certificacoes obrigatorias', 'Capacitação e Desenvolvimento', 'Certificações Obrigatórias'),
  ('integracao de novos empregados', 'Capacitação e Desenvolvimento', 'Integração de Novos Empregados'),
  ('desenvolvimento de liderancas', 'Capacitação e Desenvolvimento', 'Desenvolvimento de Lideranças'),
  ('educacao corporativa', 'Capacitação e Desenvolvimento', 'Educação Corporativa'),
  ('reembolso educacional', 'Capacitação e Desenvolvimento', 'Reembolso Educacional'),
  ('equidade de genero', 'Igualdade, Diversidade e Categorias Especiais', 'Equidade de Gênero'),
  ('igualdade salarial entre homens e mulheres', 'Igualdade, Diversidade e Categorias Especiais', 'Igualdade Salarial entre Homens e Mulheres'),
  ('igualdade salarial', 'Igualdade, Diversidade e Categorias Especiais', 'Igualdade Salarial entre Homens e Mulheres'),
  ('combate ao assedio', 'Igualdade, Diversidade e Categorias Especiais', 'Combate ao Assédio'),
  ('pcd', 'Igualdade, Diversidade e Categorias Especiais', 'PCD'),
  ('pessoa com deficiencia', 'Igualdade, Diversidade e Categorias Especiais', 'PCD'),
  ('diversidade racial', 'Igualdade, Diversidade e Categorias Especiais', 'Diversidade Racial'),
  ('pessoas trans lgbtqia+', 'Igualdade, Diversidade e Categorias Especiais', 'Pessoas Trans/LGBTQIA+'),
  ('pessoas trans', 'Igualdade, Diversidade e Categorias Especiais', 'Pessoas Trans/LGBTQIA+'),
  ('lgbtqia+', 'Igualdade, Diversidade e Categorias Especiais', 'Pessoas Trans/LGBTQIA+'),
  ('lgbtqia', 'Igualdade, Diversidade e Categorias Especiais', 'Pessoas Trans/LGBTQIA+'),
  ('trabalhadores migrantes refugiados', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalhadores Migrantes/Refugiados'),
  ('migrantes', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalhadores Migrantes/Refugiados'),
  ('refugiados', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalhadores Migrantes/Refugiados'),
  ('trabalhadores migrantes', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalhadores Migrantes/Refugiados'),
  ('trabalhadores idosos', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalhadores Idosos'),
  ('idosos', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalhadores Idosos'),
  ('apoio a vitimas de violencia domestica', 'Igualdade, Diversidade e Categorias Especiais', 'Apoio a Vítimas de Violência Doméstica'),
  ('violencia domestica', 'Igualdade, Diversidade e Categorias Especiais', 'Apoio a Vítimas de Violência Doméstica'),
  ('trabalho do menor aprendiz', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalho do Menor/Aprendiz'),
  ('trabalho do menor', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalho do Menor/Aprendiz'),
  ('aprendiz', 'Igualdade, Diversidade e Categorias Especiais', 'Trabalho do Menor/Aprendiz'),
  ('monitoramento e uso de sistemas', 'Tecnologia, Dados e Propriedade Intelectual', 'Monitoramento e Uso de Sistemas'),
  ('monitoramento eletronico', 'Tecnologia, Dados e Propriedade Intelectual', 'Monitoramento e Uso de Sistemas'),
  ('videomonitoramento biometria', 'Tecnologia, Dados e Propriedade Intelectual', 'Videomonitoramento/Biometria'),
  ('videomonitoramento', 'Tecnologia, Dados e Propriedade Intelectual', 'Videomonitoramento/Biometria'),
  ('biometria', 'Tecnologia, Dados e Propriedade Intelectual', 'Videomonitoramento/Biometria'),
  ('inteligencia artificial', 'Tecnologia, Dados e Propriedade Intelectual', 'Inteligência Artificial'),
  ('ia', 'Tecnologia, Dados e Propriedade Intelectual', 'Inteligência Artificial'),
  ('correio eletronico e ferramentas corporativas', 'Tecnologia, Dados e Propriedade Intelectual', 'Correio Eletrônico e Ferramentas Corporativas'),
  ('correio eletronico', 'Tecnologia, Dados e Propriedade Intelectual', 'Correio Eletrônico e Ferramentas Corporativas'),
  ('e mail corporativo', 'Tecnologia, Dados e Propriedade Intelectual', 'Correio Eletrônico e Ferramentas Corporativas'),
  ('equipamentos tecnologicos fornecidos', 'Tecnologia, Dados e Propriedade Intelectual', 'Equipamentos Tecnológicos Fornecidos'),
  ('equipamentos tecnologicos', 'Tecnologia, Dados e Propriedade Intelectual', 'Equipamentos Tecnológicos Fornecidos'),
  ('propriedade intelectual', 'Tecnologia, Dados e Propriedade Intelectual', 'Propriedade Intelectual'),
  ('propriedade intelectual e responsabilidade', 'Tecnologia, Dados e Propriedade Intelectual', 'Propriedade Intelectual'),
  ('protecao de dados lgpd', 'Tecnologia, Dados e Propriedade Intelectual', 'Proteção de Dados (LGPD)'),
  ('protecao de dados', 'Tecnologia, Dados e Propriedade Intelectual', 'Proteção de Dados (LGPD)'),
  ('lgpd', 'Tecnologia, Dados e Propriedade Intelectual', 'Proteção de Dados (LGPD)'),
  ('propriedade de dados e sistemas', 'Tecnologia, Dados e Propriedade Intelectual', 'Proteção de Dados (LGPD)'),
  ('seguranca da informacao e confidencialidade', 'Tecnologia, Dados e Propriedade Intelectual', 'Segurança da Informação e Confidencialidade'),
  ('seguranca da informacao', 'Tecnologia, Dados e Propriedade Intelectual', 'Segurança da Informação e Confidencialidade'),
  ('confidencialidade', 'Tecnologia, Dados e Propriedade Intelectual', 'Segurança da Informação e Confidencialidade'),
  ('vigencia', 'Disposições Gerais e Vigência', 'Vigência'),
  ('vigencia do instrumento coletivo', 'Disposições Gerais e Vigência', 'Vigência'),
  ('vigencia e data base', 'Disposições Gerais e Vigência', 'Vigência'),
  ('prorrogacao', 'Disposições Gerais e Vigência', 'Prorrogação'),
  ('revisao', 'Disposições Gerais e Vigência', 'Revisão'),
  ('denuncia do instrumento', 'Disposições Gerais e Vigência', 'Denúncia do Instrumento'),
  ('abrangencia', 'Disposições Gerais e Vigência', 'Abrangência'),
  ('abrangencia da categoria e territorial', 'Disposições Gerais e Vigência', 'Abrangência'),
  ('abrangencia da cct', 'Disposições Gerais e Vigência', 'Abrangência'),
  ('abrangencia e aplicacao', 'Disposições Gerais e Vigência', 'Abrangência'),
  ('abrangencia territorial', 'Disposições Gerais e Vigência', 'Abrangência'),
  ('validade e abrangencia', 'Disposições Gerais e Vigência', 'Abrangência'),
  ('validade e fundamentacao legal', 'Disposições Gerais e Vigência', 'Abrangência'),
  ('hierarquia de normas', 'Disposições Gerais e Vigência', 'Hierarquia de Normas'),
  ('apoio e prevalencia de clausulas', 'Disposições Gerais e Vigência', 'Hierarquia de Normas'),
  ('interpretacao do instrumento coletivo', 'Disposições Gerais e Vigência', 'Interpretação do Instrumento Coletivo'),
  ('interpretacao', 'Disposições Gerais e Vigência', 'Interpretação do Instrumento Coletivo'),
  ('casos omissos', 'Disposições Gerais e Vigência', 'Casos Omissos'),
  ('integracao das clausulas', 'Disposições Gerais e Vigência', 'Integração das Cláusulas'),
  ('revogacao', 'Disposições Gerais e Vigência', 'Revogação'),
  ('foro de eleicao', 'Disposições Gerais e Vigência', 'Foro de Eleição'),
  ('condicoes gerais', 'Disposições Gerais e Vigência', 'Condições Gerais'),
  ('alteracao e extincao do acordo', 'Disposições Gerais e Vigência', 'Condições Gerais'),
  ('outras', 'Disposições Gerais e Vigência', 'Outras'),
  ('outro', 'Disposições Gerais e Vigência', 'Outras');

-- 1) Atualiza clausulas.categoria/subcategoria (cache) para os novos nomes canônicos
update clausulas c
set categoria = m.categoria,
    subcategoria = m.subcategoria
from _mapa_subcategorias_v2 m
where _normalizar_chave(c.subcategoria) = m.chave
  and (c.categoria <> m.categoria or c.subcategoria <> m.subcategoria);

-- 2) Remapeia clausula_categorias (principal e adicionais), evitando violar o UNIQUE
--    (clausula_id, categoria, subcategoria) em caso de colisão após o remapeamento.
with alvo as (
  select cc.id as cc_id, cc.clausula_id, m.categoria as nova_categoria, m.subcategoria as nova_subcategoria
  from clausula_categorias cc
  join _mapa_subcategorias_v2 m on m.chave = _normalizar_chave(cc.subcategoria)
  where cc.categoria <> m.categoria or cc.subcategoria <> m.subcategoria
),
duplicatas as (
  select a.cc_id
  from alvo a
  where exists (
    select 1 from clausula_categorias other
    where other.clausula_id = a.clausula_id
      and other.categoria = a.nova_categoria
      and other.subcategoria = a.nova_subcategoria
      and other.id <> a.cc_id
  )
)
delete from clausula_categorias where id in (select cc_id from duplicatas);

with alvo as (
  select cc.id as cc_id, m.categoria as nova_categoria, m.subcategoria as nova_subcategoria
  from clausula_categorias cc
  join _mapa_subcategorias_v2 m on m.chave = _normalizar_chave(cc.subcategoria)
  where cc.categoria <> m.categoria or cc.subcategoria <> m.subcategoria
)
update clausula_categorias cc
set categoria = a.nova_categoria, subcategoria = a.nova_subcategoria
from alvo a
where cc.id = a.cc_id;

-- 3) Relatório de cláusulas ainda não reconhecidas pelo mapa (revisão manual)
select c.id, c.numero, c.titulo, c.categoria as categoria_atual, c.subcategoria as subcategoria_atual,
       i.nome as instrumento
from clausulas c
join instrumentos i on i.id = c.instrumento_id
where not exists (
  select 1 from _mapa_subcategorias_v2 m where m.chave = _normalizar_chave(c.subcategoria)
)
order by i.nome, c.numero;
