// Utilitário de ordenação de cláusulas — suporta ordinais em português até 200
// e números arábicos (1, 2, 3...) e romanos (I, II, III...)

const ORDINAIS = {
  'PRIMEIRA': 1, 'SEGUNDA': 2, 'TERCEIRA': 3, 'QUARTA': 4, 'QUINTA': 5,
  'SEXTA': 6, 'SÉTIMA': 7, 'OITAVA': 8, 'NONA': 9, 'DÉCIMA': 10,
  'DÉCIMA PRIMEIRA': 11, 'DÉCIMA SEGUNDA': 12, 'DÉCIMA TERCEIRA': 13,
  'DÉCIMA QUARTA': 14, 'DÉCIMA QUINTA': 15, 'DÉCIMA SEXTA': 16,
  'DÉCIMA SÉTIMA': 17, 'DÉCIMA OITAVA': 18, 'DÉCIMA NONA': 19,
  'VIGÉSIMA': 20, 'VIGÉSIMA PRIMEIRA': 21, 'VIGÉSIMA SEGUNDA': 22,
  'VIGÉSIMA TERCEIRA': 23, 'VIGÉSIMA QUARTA': 24, 'VIGÉSIMA QUINTA': 25,
  'VIGÉSIMA SEXTA': 26, 'VIGÉSIMA SÉTIMA': 27, 'VIGÉSIMA OITAVA': 28,
  'VIGÉSIMA NONA': 29, 'TRIGÉSIMA': 30, 'TRIGÉSIMA PRIMEIRA': 31,
  'TRIGÉSIMA SEGUNDA': 32, 'TRIGÉSIMA TERCEIRA': 33, 'TRIGÉSIMA QUARTA': 34,
  'TRIGÉSIMA QUINTA': 35, 'TRIGÉSIMA SEXTA': 36, 'TRIGÉSIMA SÉTIMA': 37,
  'TRIGÉSIMA OITAVA': 38, 'TRIGÉSIMA NONA': 39, 'QUADRAGÉSIMA': 40,
  'QUADRAGÉSIMA PRIMEIRA': 41, 'QUADRAGÉSIMA SEGUNDA': 42, 'QUADRAGÉSIMA TERCEIRA': 43,
  'QUADRAGÉSIMA QUARTA': 44, 'QUADRAGÉSIMA QUINTA': 45, 'QUADRAGÉSIMA SEXTA': 46,
  'QUADRAGÉSIMA SÉTIMA': 47, 'QUADRAGÉSIMA OITAVA': 48, 'QUADRAGÉSIMA NONA': 49,
  'QUINQUAGÉSIMA': 50, 'QUINQUAGÉSIMA PRIMEIRA': 51, 'QUINQUAGÉSIMA SEGUNDA': 52,
  'QUINQUAGÉSIMA TERCEIRA': 53, 'QUINQUAGÉSIMA QUARTA': 54, 'QUINQUAGÉSIMA QUINTA': 55,
  'QUINQUAGÉSIMA SEXTA': 56, 'QUINQUAGÉSIMA SÉTIMA': 57, 'QUINQUAGÉSIMA OITAVA': 58,
  'QUINQUAGÉSIMA NONA': 59, 'SEXAGÉSIMA': 60, 'SEXAGÉSIMA PRIMEIRA': 61,
  'SEXAGÉSIMA SEGUNDA': 62, 'SEXAGÉSIMA TERCEIRA': 63, 'SEXAGÉSIMA QUARTA': 64,
  'SEXAGÉSIMA QUINTA': 65, 'SEXAGÉSIMA SEXTA': 66, 'SEXAGÉSIMA SÉTIMA': 67,
  'SEXAGÉSIMA OITAVA': 68, 'SEXAGÉSIMA NONA': 69, 'SEPTUAGÉSIMA': 70,
  'SEPTUAGÉSIMA PRIMEIRA': 71, 'SEPTUAGÉSIMA SEGUNDA': 72, 'SEPTUAGÉSIMA TERCEIRA': 73,
  'SEPTUAGÉSIMA QUARTA': 74, 'SEPTUAGÉSIMA QUINTA': 75, 'SEPTUAGÉSIMA SEXTA': 76,
  'SEPTUAGÉSIMA SÉTIMA': 77, 'SEPTUAGÉSIMA OITAVA': 78, 'SEPTUAGÉSIMA NONA': 79,
  'OCTAGÉSIMA': 80, 'OCTAGÉSIMA PRIMEIRA': 81, 'OCTAGÉSIMA SEGUNDA': 82,
  'OCTAGÉSIMA TERCEIRA': 83, 'OCTAGÉSIMA QUARTA': 84, 'OCTAGÉSIMA QUINTA': 85,
  'OCTAGÉSIMA SEXTA': 86, 'OCTAGÉSIMA SÉTIMA': 87, 'OCTAGÉSIMA OITAVA': 88,
  'OCTAGÉSIMA NONA': 89, 'NONAGÉSIMA': 90, 'NONAGÉSIMA PRIMEIRA': 91,
  'NONAGÉSIMA SEGUNDA': 92, 'NONAGÉSIMA TERCEIRA': 93, 'NONAGÉSIMA QUARTA': 94,
  'NONAGÉSIMA QUINTA': 95, 'NONAGÉSIMA SEXTA': 96, 'NONAGÉSIMA SÉTIMA': 97,
  'NONAGÉSIMA OITAVA': 98, 'NONAGÉSIMA NONA': 99,
  'CENTÉSIMA': 100, 'CENTÉSIMA PRIMEIRA': 101, 'CENTÉSIMA SEGUNDA': 102,
  'CENTÉSIMA TERCEIRA': 103, 'CENTÉSIMA QUARTA': 104, 'CENTÉSIMA QUINTA': 105,
  'CENTÉSIMA SEXTA': 106, 'CENTÉSIMA SÉTIMA': 107, 'CENTÉSIMA OITAVA': 108,
  'CENTÉSIMA NONA': 109, 'CENTÉSIMA DÉCIMA': 110,
  'CENTÉSIMA DÉCIMA PRIMEIRA': 111, 'CENTÉSIMA DÉCIMA SEGUNDA': 112,
  'CENTÉSIMA DÉCIMA TERCEIRA': 113, 'CENTÉSIMA DÉCIMA QUARTA': 114,
  'CENTÉSIMA DÉCIMA QUINTA': 115, 'CENTÉSIMA DÉCIMA SEXTA': 116,
  'CENTÉSIMA DÉCIMA SÉTIMA': 117, 'CENTÉSIMA DÉCIMA OITAVA': 118,
  'CENTÉSIMA DÉCIMA NONA': 119, 'CENTÉSIMA VIGÉSIMA': 120,
  'CENTÉSIMA VIGÉSIMA PRIMEIRA': 121, 'CENTÉSIMA VIGÉSIMA SEGUNDA': 122,
  'CENTÉSIMA VIGÉSIMA TERCEIRA': 123, 'CENTÉSIMA VIGÉSIMA QUARTA': 124,
  'CENTÉSIMA VIGÉSIMA QUINTA': 125, 'CENTÉSIMA VIGÉSIMA SEXTA': 126,
  'CENTÉSIMA VIGÉSIMA SÉTIMA': 127, 'CENTÉSIMA VIGÉSIMA OITAVA': 128,
  'CENTÉSIMA VIGÉSIMA NONA': 129, 'CENTÉSIMA TRIGÉSIMA': 130,
  'CENTÉSIMA TRIGÉSIMA PRIMEIRA': 131, 'CENTÉSIMA TRIGÉSIMA SEGUNDA': 132,
  'CENTÉSIMA TRIGÉSIMA TERCEIRA': 133, 'CENTÉSIMA TRIGÉSIMA QUARTA': 134,
  'CENTÉSIMA TRIGÉSIMA QUINTA': 135, 'CENTÉSIMA TRIGÉSIMA SEXTA': 136,
  'CENTÉSIMA TRIGÉSIMA SÉTIMA': 137, 'CENTÉSIMA TRIGÉSIMA OITAVA': 138,
  'CENTÉSIMA TRIGÉSIMA NONA': 139, 'CENTÉSIMA QUADRAGÉSIMA': 140,
  'CENTÉSIMA QUADRAGÉSIMA PRIMEIRA': 141, 'CENTÉSIMA QUADRAGÉSIMA SEGUNDA': 142,
  'CENTÉSIMA QUADRAGÉSIMA TERCEIRA': 143, 'CENTÉSIMA QUADRAGÉSIMA QUARTA': 144,
  'CENTÉSIMA QUADRAGÉSIMA QUINTA': 145, 'CENTÉSIMA QUADRAGÉSIMA SEXTA': 146,
  'CENTÉSIMA QUADRAGÉSIMA SÉTIMA': 147, 'CENTÉSIMA QUADRAGÉSIMA OITAVA': 148,
  'CENTÉSIMA QUADRAGÉSIMA NONA': 149, 'CENTÉSIMA QUINQUAGÉSIMA': 150,
  'CENTÉSIMA QUINQUAGÉSIMA PRIMEIRA': 151, 'CENTÉSIMA QUINQUAGÉSIMA SEGUNDA': 152,
  'CENTÉSIMA QUINQUAGÉSIMA TERCEIRA': 153, 'CENTÉSIMA QUINQUAGÉSIMA QUARTA': 154,
  'CENTÉSIMA QUINQUAGÉSIMA QUINTA': 155, 'CENTÉSIMA QUINQUAGÉSIMA SEXTA': 156,
  'CENTÉSIMA QUINQUAGÉSIMA SÉTIMA': 157, 'CENTÉSIMA QUINQUAGÉSIMA OITAVA': 158,
  'CENTÉSIMA QUINQUAGÉSIMA NONA': 159, 'CENTÉSIMA SEXAGÉSIMA': 160,
  'CENTÉSIMA SEXAGÉSIMA PRIMEIRA': 161, 'CENTÉSIMA SEXAGÉSIMA SEGUNDA': 162,
  'CENTÉSIMA SEXAGÉSIMA TERCEIRA': 163, 'CENTÉSIMA SEXAGÉSIMA QUARTA': 164,
  'CENTÉSIMA SEXAGÉSIMA QUINTA': 165, 'CENTÉSIMA SEXAGÉSIMA SEXTA': 166,
  'CENTÉSIMA SEXAGÉSIMA SÉTIMA': 167, 'CENTÉSIMA SEXAGÉSIMA OITAVA': 168,
  'CENTÉSIMA SEXAGÉSIMA NONA': 169, 'CENTÉSIMA SEPTUAGÉSIMA': 170,
  'CENTÉSIMA SEPTUAGÉSIMA PRIMEIRA': 171, 'CENTÉSIMA SEPTUAGÉSIMA SEGUNDA': 172,
  'CENTÉSIMA SEPTUAGÉSIMA TERCEIRA': 173, 'CENTÉSIMA SEPTUAGÉSIMA QUARTA': 174,
  'CENTÉSIMA SEPTUAGÉSIMA QUINTA': 175, 'CENTÉSIMA SEPTUAGÉSIMA SEXTA': 176,
  'CENTÉSIMA SEPTUAGÉSIMA SÉTIMA': 177, 'CENTÉSIMA SEPTUAGÉSIMA OITAVA': 178,
  'CENTÉSIMA SEPTUAGÉSIMA NONA': 179, 'CENTÉSIMA OCTAGÉSIMA': 180,
  'CENTÉSIMA OCTAGÉSIMA PRIMEIRA': 181, 'CENTÉSIMA OCTAGÉSIMA SEGUNDA': 182,
  'CENTÉSIMA OCTAGÉSIMA TERCEIRA': 183, 'CENTÉSIMA OCTAGÉSIMA QUARTA': 184,
  'CENTÉSIMA OCTAGÉSIMA QUINTA': 185, 'CENTÉSIMA OCTAGÉSIMA SEXTA': 186,
  'CENTÉSIMA OCTAGÉSIMA SÉTIMA': 187, 'CENTÉSIMA OCTAGÉSIMA OITAVA': 188,
  'CENTÉSIMA OCTAGÉSIMA NONA': 189, 'CENTÉSIMA NONAGÉSIMA': 190,
  'CENTÉSIMA NONAGÉSIMA PRIMEIRA': 191, 'CENTÉSIMA NONAGÉSIMA SEGUNDA': 192,
  'CENTÉSIMA NONAGÉSIMA TERCEIRA': 193, 'CENTÉSIMA NONAGÉSIMA QUARTA': 194,
  'CENTÉSIMA NONAGÉSIMA QUINTA': 195, 'CENTÉSIMA NONAGÉSIMA SEXTA': 196,
  'CENTÉSIMA NONAGÉSIMA SÉTIMA': 197, 'CENTÉSIMA NONAGÉSIMA OITAVA': 198,
  'CENTÉSIMA NONAGÉSIMA NONA': 199, 'DUCENTÉSIMA': 200,
}

// Converte número romano para arábico
function romanToInt(s) {
  const vals = { I:1, V:5, X:10, L:50, C:100, D:500, M:1000 }
  let result = 0
  for (let i = 0; i < s.length; i++) {
    const cur = vals[s[i]]
    const next = vals[s[i+1]]
    if (!cur) return null
    if (next && cur < next) result -= cur
    else result += cur
  }
  return result
}

export function toNumeroOrdinal(n) {
  if (!n) return 9999
  const str = String(n).trim()

  // Número arábico puro: "1", "2", "42"
  const arab = str.match(/^(\d+)/)
  if (arab) return parseInt(arab[1])

  // Ordinal escrito por extenso
  const upper = str.toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    // Reaplica acentos para bater com o dicionário
  const upperAcent = str.toUpperCase()
  if (ORDINAIS[upperAcent] !== undefined) return ORDINAIS[upperAcent]

  // Tenta match parcial para casos como "CLÁUSULA DÉCIMA SEGUNDA"
  for (const [key, val] of Object.entries(ORDINAIS)) {
    if (upperAcent.includes(key)) return val
  }

  // Romano: I, II, III, IV, V...
  const roman = romanToInt(str.toUpperCase().replace(/[^IVXLCDM]/g, ''))
  if (roman && roman > 0 && roman <= 300) return roman

  return 9999
}

export function ordenarClausulas(clausulas) {
  return [...clausulas].sort((a, b) => toNumeroOrdinal(a.numero) - toNumeroOrdinal(b.numero))
}
